## 条款08：别让异常逃离析构函数
C++并不禁止析构函数抛出异常，但不鼓励这种做法。考虑如下代码：
```c++
class Widget {
public:
    ...
    ~Widget() { ... }       // 假设这个可能吐出一个异常
};
void doSomething(){
    std::vector<Widget> v;
}                           // v在这里被自动销毁
```
当`v`被销毁，它有责任销毁其内含的所有`Widget`。假设`v`内含十个`Widgets`，而在析构第一个元素期间，有个异常被抛出。其他九个`Widgets`还是应该被销毁（否则他们保存的任何资源都会发生泄漏），因此v应该调用它们各个析构函数。但假设在那些调用期间，第二个`Widgets`析构函数又抛出异常。现在有两个异常被抛出，这对C++而言太多了，在这种情况下，要么程序结束执行，要么导致不确定行为。

但如果析构函数必须执行一个动作，而该动作可能会在失败时抛出异常，该怎么办？举个例子，假设使用一个类负责数据库连接：
```c++
class DBConnection { 
public:
    ...
    static DBConnection create();  // 返回DBConnection对象
    void close();                  // 关闭连接，失败则抛出异常
};
```
为了确保用户不会忘记在`DBConnection`对象身上调用`close()`，一个合理的想法是创建一个用来管理`DBConnection`资源的类，并在其析构函数中调用`close()`：
```c++
class DBConn {      // 这个类用来管理DBConnection对象 
public:
    ...
    DBConn(const DBConnection& db) {
        this->db = db;
    }
    ~DBConn()       // 确保数据库连接总是会被关闭
    {
　　    db.close();
    }
private:
    DBConnection db;
};
```
用户可以这样使用这个类：
```c++
{
    ...
    DBConn dbc(DBConnection::create());
    ...
}
```
这行代码是可以正常工作的。但如果`DBConn`的析构函数调用`db.close()`导致异常，它就会传播这个异常，也就是允许这个异常离开这个析构函数，这会造成难以处理的问题。有两个方法可以避免这一问题：
### 如果`close()`抛出异常就结束程序，可以通过调用`abort()`完成：
```c++
DBConn::~DBConn()
{
    try { db.close(); }
    catch ( ... ) {
        // 这里最好记录下对close的失败调用
        std::abort();
    }
}
```
如果程序遭遇一个在析构期间发生的错误而无法继续执行，强制结束程序是个合理选项，毕竟它可以阻止异常从析构函数传播出去（那会导致不明确的行为）。也就是说调用`abort()`可以阻止产生不明确行为。
### 吞下因调用`close()`而抛出异常：
```c++
DBConn::~DBConn
{
    try { db.close(); }
    catch ( ... ) {
        // 这里最好记录下对close的失败调用
    }
}
```
一般而言，吞下异常是个坏主意，因为这种做法压制了某些操作失败的重要信息，但有时吞下异常比草率结束程序或导致未定义行为要好些。

一个较佳的策略是重新设计`DBConn`的接口，试其用户有机会对可能出现的问题作出反应。例如`DBConn`自己可以提供一个`close()`函数。`DBConn`也可以追踪其所管理的`DBConnection`是否已经被关闭，并在答案为否的情况下由`DBConn`的析构函数关闭。当`DBConn`的析构函数调用`close()`失败，我们又将进行强迫结束程序或吞下异常的操作：
```c++
class DBConn {
public:
    ...
    void close() //供客户使用的新函数
    {
        db.close();
        closed = true;
    }
    ~DBConn() {
        if (!closed) {
            try {
                  db.close();   // 关闭连接(如果客户不调用DBConn::close)
            }
            catch (...) {
                // 如果close()失败，记录下来并结束程序或吞下异常。
                ...
           }
        }
    }
private:
    DBConnection db;
    bool closed;
};
```
### 请记住
* 析构函数绝对不要突出异常。如果一个被析构函数调用的函数可能抛出异常，析构函数应该捕捉这些异常，然后结束程序或吞下异常。
* 如果用户需要对某个函数运行期间抛出的异常做出反应，那么类应该提供一个普通函数（而不是在析构函数中）执行这个操作。